repository: idealdestructor/doraemon
repository_url: https://github.com/idealdestructor/doraemon

timezone:
lang: zh_CN

title: 哆啦a梦搜索
alias_en: Doraemon Search
alias_cn: 哆啦a梦搜索
description: 析构理想
keywords: 搜索导航,哆啦,哆啦a梦
url: https://so.idealdestructor.com/
established_at: "2019-06-11T00:00+08:00"

author: IdealDestructor
author_url: https://deqiang.wang
organization: ~Ideal()
organization_url: http://www.idealdestructor.com
contact: contact[at]idealdestructor[dot]com

image: https://so.idealdestructor.com/images/logo.gif
logo: https://so.idealdestructor.com/images/logo.gif
logo_dark: https://so.idealdestructor.com/images/logo-dark.svg
logo_white: https://so.idealdestructor.com/images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor